blank_issues_enabled: false
contact_links:
  - name: ðŸ“š Documentation
    url: https://github.com/dsh0416/tapsdk-pc.js/tree/main/docs
    about: Check the documentation for guides and API reference
